### ISSUE TITLE
Morning Session: Peer-to-peer code review

### ISSUE THREAD

**Issue by kelvinbush** [mavericks-db/awesome-books#3]
In our morning session we came across the following issues, we suggest you make the following changes for a cleaner code base:

- Please update the link to  the live version of the page in your readme file.
- Consider using camel case when declaring JavaScript functions.
- You should consider linking the script JavaScript file at the end of the `body`  tag to allow all the elements to load first before manipulating them with the DOM.

**Comment by mavericks-db** [comment]
Hi there! 👍  Thanks for the review. 😃 . Changes are done. Have a great day!
